server:
  port: "8080"
  grpc_port: "50051"
  env: "development"

user_service:
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "password"
    dbname: "user_db"
    sslmode: "disable"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

product_service:
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "password"
    dbname: "product_db"
    sslmode: "disable"

order_service:
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "password"
    dbname: "order_db"
    sslmode: "disable"

payment_service:
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "password"
    dbname: "payment_db"
    sslmode: "disable"

inventory_service:
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "password"
    dbname: "inventory_db"
    sslmode: "disable"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

notification_service:
  mongo:
    uri: "mongodb://localhost:27017"
    database: "notification_db"
